version: 2.1
jobs:
  build:
    macos:
      xcode: '11.6.0'
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: ios beta
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: yarn install
      - run: bundle check || bundle install --path vendor/bundle
      - run: yarn pod-install
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
            - node_modules
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_artifacts:
          path: build
      - store_test_results:
          path: output/scan

workflows:
  build-test-adhoc:
    jobs:
      - build:
        filters:
          branches:
            only: feature/fastlane_ci
